//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bekle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USED_TESTS
    {
        public int user_id { get; set; }
        public string test_id { get; set; }
        public string test_device { get; set; }
        public string test_desc { get; set; }
    }
}
